config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/super', as: 'rails_admin'

  def scheme
    if @env['HTTPS'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SSL'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SCHEME']
      @env['HTTP_X_FORWARDED_SCHEME']
    elsif @env['HTTP_X_FORWARDED_PROTO']
      @env['HTTP_X_FORWARDED_PROTO'].split(',')[0]
    else
      @env["rack.url_scheme"]
    end
  end

  def ssl?
    scheme == 'https'
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :appointments
  end

  post 'pay2go/return'
  post 'pay2go/notify'

  post "/paypal/webhook" => "paypal#webhook"
  post "/paypal/redirect" => "paypal#redirect" # for paypal return

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}
  resources :messages

  resources :users do
    member do
      get :classes
      get :changepassword
      get :remark
      get :editprofile
      get :mytutor
      post :mytutor
    end
    resources :orders do
      member do
        post :checkout_pay2go
        post :checkout_paypal
      end
    end
    resources :available_section, controller: 'user_available_sections'
    member do
      get 'profile'
    end
  end

  resources :teachers do
    member do
      get 'classes' => 'teachers#classes'
      get 'profile' => 'teachers#profile'
      post 'profile' => 'teachers#profile#create'
      get 'calendar' => 'teachers#calendar'
      get 'introduce' => 'teachers#introduce'
      get 'price' => 'teachers#price'
      get 'education' => 'teachers#education'
      get 'youtube' => 'teachers#youtube'
      get 'gathering' => 'teachers#gathering'
    end
    resources :available_section
  end
  get 'apply_teacher_file' => 'teachers#apply_teacher_file'

  resources :appointments do
    resources :evaluations
  end

  resources :student_reservation
  post 'free_trial' =>'student_reservation#free_trial'

  resources :teacher_calendars do
    get 'teacher_available_section' => 'teacher_calendars#teacher_available_section'
    get 'booked_section' => 'teacher_calendars#booked_section'
  end

  get  'scholarship'=> "welcome#scholarship"
  get  'apply_teacher'=> "welcome#apply_teacher"
  get  'teacherwall'=>"welcome#index"
  root 'welcome#mainindex'
  get 'thankyou' => "orders#thankyou"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  has_many :teacher_languageships
  has_many :languages, through: :teacher_languageships
  has_many :available_sections
  has_many :appointments
  has_many :evaluations, as: :evaluatable
  has_many :experiences
  has_many :certificates
  has_many :educations
  has_many :orders
  has_many :appointments
  accepts_nested_attributes_for :teacher_languageships, allow_destroy: true
  accepts_nested_attributes_for :languages, allow_destroy: true
  accepts_nested_attributes_for :experiences, allow_destroy: true
  accepts_nested_attributes_for :certificates, allow_destroy: true
  accepts_nested_attributes_for :educations, allow_destroy: true

  def uniq_language
    array = []
    params[:teacher][:languages_attributes].map { |x| array << x[:language] }
    array.uniq
  end

  def youtube_website
    youtube.split("=").last
  end

  def one_fee_exchange_to(iso_to)

    Money.new(one_fee*100, "USD").exchange_to(iso_to)
  end

  def five_fee_exchange_to(iso_to)
    Money.new(five_fee*100, "USD").exchange_to(iso_to)
  end

  def ten_fee_exchange_to(iso_to)
    Money.new(ten_fee*100, "USD").exchange_to(iso_to)
  end

  # def check_fee(fee,session)
  #   fee = (fee.to_i)/(session.to_i)
  #
  #   if fee == self.one_fee || fee == self.five_fee || fee == self.ten_fee
  #     return true
  #   else
  #     return false
  #   end
  # end

  # def hangouts_url
  #   if self.hangouts_url.blank?

  #     charset = (0...4).map { ('a'..'z').to_a[ rand(26)] }.join
  #     url =  "https://talkgadget.google.com/hangouts/_/i"+charset+"m5jzffaheagjkaa5wzj7y2?hl=zh-TW"
  #     self.hangouts_url = url
  #   end
  # end

  def appointment_check(start_time, end_time)
    self.appointments.where("(start >= ? and end <= ?) or (start >= ?  and start < ?) or (end > ?  and end <= ?) or (start < ? and end > ?)",
                            start_time, end_time,
                            start_time, end_time,
                            start_time, end_time,
                            start_time, end_time).exists?
  end

  def find_available_days
    @days = []
    self.available_sections.each do |available_section|
      @start = available_section.start
      @end = available_section.end
      for i in 0..((@end - @start)/1.day).to_i
        @days << @start + i.days
      end
    end
    @days.select{|x| x>= Time.current.in_time_zone + 1.hours }.map{|x|x.to_date}.uniq.sort
    # @available_section_times.uniq.sort.select{|x| [x[0],x[1]] if x[0]>= Time.current.in_time_zone+12.hours }
  end

  def find_available_times(pickedday= Time.current.in_time_zone,section=2)
    @available_section_times = []
    @pickedday = pickedday.to_date.in_time_zone
    @pickedday_start = @pickedday.beginning_of_day
    @pickedday_end = @pickedday.end_of_day
    # type 要輸入1 or 2 試上 或正式課
    available_sections.each do |available_section|
      for i in 0..((available_section.end - available_section.start) / 24.hours).to_i+1
        @forday = available_section.start.to_date + i.days
        if @forday == @pickedday.to_date
          if available_section.start >= @pickedday_start && available_section.start < @pickedday_end && available_section.end > @pickedday_end
            block = (((@pickedday_end + 1) - available_section.start) / 30.minute).to_i - 1
            x = available_section.start
          end
          if available_section.start <  @pickedday_start && available_section.end > @pickedday_end
            block = (((@pickedday_end + 1) - @pickedday_start) / 30.minute).to_i - 1
            x = @pickedday_start
          end

          if available_section.end > @pickedday_start && available_section.end <= @pickedday_end && available_section.start < @pickedday_start
            block = ((available_section.end - @pickedday_start) / 30.minute).to_i - 1
            x = @pickedday_start
          end
          if available_section.start >= @pickedday_start && available_section.end < @pickedday_end
            block = ((available_section.end - available_section.start) / 30.minute).to_i - 1
            x = available_section.start
          end
          unless block.nil?
            for i in 0..block
              @available_section_times << [ x , x + (section* 30.minute)]
              x += 30.minute
            end
          end
          # if @available_section_times.present?
          # @available_section_times.pop if @available_section_times.last.last > available_section.end
          #   end
          @available_section_times.pop if section == 2 && block != nil
        end
      end
    end
    @available_section_times.uniq.select{|x| x unless self.appointment_check(x[0], x[1])}.sort.select{|x| x[0]>= Time.current.in_time_zone + 1.hours}.map{|x| x[0].strftime('%R %p')+" - "+x[1].strftime('%R %p') }
  end
  # @available_section_times.uniq.select{|x| x unless self.appointment_check(x[0], x[1])}.sort.select{|x| x[0]>= Time.current.in_time_zone+12.hours }.map{|x| x[0].strftime('%r')+" - "+x[1].strftime('%r') }
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    if user_signed_in?
      result = current_user.connect_to_facebook(request.env["omniauth.auth"])
      if result =='update'
        set_flash_message(:notice, :updated, :kind => "Facebook") if is_navigational_format?
      elsif result
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        set_flash_message(:notice, :failure, :kind => "Facebook", :reason => 'already exist') if is_navigational_format?
      end
      redirect_to profile_user_path(current_user)
    else
      @user = User.from_facebook_omniauth(request.env["omniauth.auth"],cookies['browser.timezone'])
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

  def failure
    redirect_to root_path
  end

  def google_oauth2
    if user_signed_in?
      result = current_user.connect_to_google_omniauth(request.env["omniauth.auth"])
      if result =='update'
        set_flash_message(:notice, :updated, :kind => "Google+") if is_navigational_format?
      elsif result
        set_flash_message(:notice, :success, :kind => "Google+") if is_navigational_format?
      else
        set_flash_message(:notice, :failure, :kind => "Google+", :reason => 'already exist') if is_navigational_format?
      end
      redirect_to profile_user_path(current_user)
    else
      @user = User.from_google_omniauth(request.env["omniauth.auth"],cookies['browser.timezone'])
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Google+") if is_navigational_format?
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
    # You need to implement the method below in your model (e.g. app/models/user.rb)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
      cookies[:scholarship] = params[:scholarship] if params[:scholarship]
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        # respond_with resource, location: after_sign_up_path_for(resource)
        if session[:previous_url] == "/apply_teacher"
          redirect_to apply_teacher_file_path
        else
          redirect_to teacherwall_path
        end
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      #  respond_with resource
      flash[:alert] = resource.errors.full_messages.each { |x| flash[x] = x }
      redirect_to :back
    end
    if resource.id.present?
      resource.time_zone = cookies['browser.timezone']
      resource.alternate_email = resource.email
      resource.save!
      if cookies[:scholarship]
        begin
          key = OpenSSL::Digest::SHA256.new('amazing_scholarship_tutor_lululala').digest
          crypt = ActiveSupport::MessageEncryptor.new(key)
          @decrypted_data = crypt.decrypt_and_verify(cookies[:scholarship])
          @old_user = User.where(email: @decrypted_data).first
          Scholarship.create(new_user_id: resource.id, user_id: @old_user.id, bonus: "90")
        rescue
        end
      end
    end
    cookies[:scholarship] = nil
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper

  def count_num(available_sections)
    @count_sections = 0
    available_sections.each do |available_section|
      @count_sections += 1 if available_section.available_section % 2 == 1
      @count_sections += (available_section.available_section / 2).to_i
    end
    @count_sections
  end

  def user_headimage(user)
    if user.image?
      image_url = user.image.url(:medium)
    elsif user.fb_pic?
      image_url = user.fb_pic
    elsif user.google_pic?
      image_url = user.google_pic
    else
      image_url = "logo.jpg"
    end
      image_tag image_url
  end

  def trail_check(user,teacher)
    disable_type = []
    disable_type << 1 if  user.user_available_sections.find_by(:teacher_id=> teacher.id).nil? || user.user_available_sections.find_by(:teacher_id=> teacher.id).trailed.nil? || user.user_available_sections.find_by(:teacher_id=> teacher.id).trailed == false
    disable_type << 2 if user.user_available_sections.find_by(:teacher_id=> teacher.id).nil? || user.user_available_sections.find_by(:teacher_id=> teacher.id).available_section < 2
    disable_type
  end

  def free_section_create(teacher_id)
    check_section = current_user.user_available_sections.find(teacher_id:teacher_id)
    if teacher_id.trial_fee == 0 && check_section.nil? && check_section.trailed == false

    end
  end
end

app/views/users/_sidebar.html.erb
<div class="col-xs-12 scheduled-head">
  <%= link_to  mytutor_user_path(current_user) ,class:"remove_a_style" do %>
      <div class="col-xs-4">
        <h4><%= current_user.appointments.count %></h4>
        <p>Scheduled</p>
      </div>
  <% end %>
  <%= link_to  mytutor_user_path(current_user) ,class:"remove_a_style" do %>
      <div class="col-xs-4">
        <h4><%= current_user.user_available_sections != 0 ? count_num(current_user.user_available_sections) : "0"%></h4>
        <p>Unschedule</p>
      </div>
  <% end %>
  <div class="col-xs-4">
    <h4><%= current_user.appointments.where("end < ?", Time.current.in_time_zone).count %></h4>
    <p>Past</p>
  </div>

</div>
<div class="col-xs-12 user-list">
  <div class = "<%= "current_tab" if current_page?(classes_user_path(current_user)) %>">
    <%= link_to "Class",classes_user_path(current_user) %>
  </div>
  <div class = "<%= "current_tab" if current_page?(mytutor_user_path(current_user)) %>">
    <%= link_to "MyTutor",mytutor_user_path(current_user) %>
  </div>
  <div class = "<%= "current_tab" if current_page?(remark_user_path(current_user)) %>">
    <%= link_to "FeedBack",remark_user_path(current_user) %>
  </div>
  <div class = "<%= "current_tab" if current_page?(profile_user_path(current_user)) %>">
    <%= link_to "EditProfile",profile_user_path(current_user) %>
  </div>
  <div class = "<%= "current_tab" if current_page?(edit_user_registration_path) %>">
    <%= link_to "ChangePassword",edit_user_registration_path %>
  </div>
</div>

app/views/users/_times_select.html.erb
<%= select({},{},@times,{}, {id:"times_select_#{t.id}" ,:class=>"selectpicker show-menu-arrow" ,"data-size" =>"5.5","data-width" =>"100%"} )%>

app/views/users/changepassword.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 text-center  col-xs-12">
      <%= render "sidebar"%>
    </div>

    <div class="col-md-7  col-xs-12">
      <div class="scheduled-content scheduled-changepassword-fix">
        <div class="scheduled-content-head">
          <h4>Change Password</h4>
        </div>
        <div class="input-group clearfix">
          <label for="#your-input" class="pull-left">New Password</label>
          <input type="text" class="form-control" aria-describedby="basic-addon1">
        </div>
        <div class="input-group clearfix">
          <label for="#your-input" class="pull-left">Confirm Password</label>
          <input type="text" class="form-control" aria-describedby="basic-addon1">
        </div>
      </div>
      <div class="editprofile-save">
        <button type="button" name="button" class="btn">SAVE</button>
      </div>
    </div>
  </div>
</div>

app/views/users/mytutor.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 text-center">
      <%= render "sidebar"%>
    </div>
    <div class="col-md-7">
      <div class="row_spical_fix">
        <% if UserAvailableSection.where(user_id:current_user).count != 0 %>
            <% UserAvailableSection.where(user_id:current_user).each do |a| %>
                <div class="col-xs-12">
                  <div class="tutor-info">
                    <div class="clearfix tutor-top">
                      <div class="info-mypic col-xs-3 pull-left col-sm-2">
                        <%= user_headimage(a.teacher.user) %>
                      </div>
                      <div class="info-eval col-xs-7 col-sm-7">
                        <p><%= a.teacher.user.last_name %> <%= a.teacher.user.first_name %></p>
                        <div id="rateYo-<%= a.teacher_id %>" ></div>
                        <span>(<%= Evaluation.where(evaluatable_type: "User", evaluated_id: a.teacher_id ).count %>)</span>
                      </div>
                      <div class=" col-xs-2 info-flag col-sm-1 col-sm-push-1 info-flag-class-fix">
                      </div>
                    </div>
                    <div class="clearfix info-tag">
                      <i class="fa fa-comment-o"></i>
                      <span>Speak:</span>
                      <span>
                        <% a.teacher.languages.each do |language| %>
                        <%= language.language %>
                        <% end %>
                      </span><br>
                              <i class="fa fa-usd"></i>
                      <span>Rate
                      </span>
                      <span class="moneyred">
                        <%= render partial: 'welcome/moneyred', locals: {t: a.teacher} %>
                      </span><br>
                      <% if  a.available_section == 1 %>
                      <h5>1 Trial</h5>
                          <% else %>
                      <h5><%= a.available_section/2 %> UnScheduled</h5>
                          <% end %>
                      <% if a.available_section == 0 %>
                          <p><%= link_to "Find a Tutor",new_user_order_path(current_user, :teacher_id =>a.teacher.id) %></p>
                      <% else %>
                          <button type="button" data-toggle="modal" data-target="#booknow-<%= a.teacher.id %>">Book Now</button>
                      <% end %>
                    </div>
                  </div>
                </div>
            <% end %>
        <% else %>
            <div class="col-xs-12">
            <%= render partial: 'recommend' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% @teachers.each do |t|%>
    <div class="modal fade teacher-modal" data-calendar-url="<%= teacher_calendar_teacher_available_section_path(t.id)%>" data-teacher-id="<%= t.id %>" id="booknow-<%= t.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Booking Teacher</h4>
          </div>
          <div class="container-fluid">
            <div class="calender-booking">
              <h6>All time listed are in your local timezone</h6>
              <div class="insert-calender">
                <div id="calendar-<%= t.id %>"></div>
              </div>
            </div>
            <div class="select-list">
              <h6>Only can pick classes after 12 hours from now</h6>
              <div class="row">
                <%#= form_for @appointment, :url => url_for(:controller => 'appointments', :action => 'create') do |x|%>
                <div class="col-xs-4">
                  <div class="time">
                    <span>Type</span>
                    <%= select({},{},options_for_select([["Normal 1hour", "2"],["Trail 30mins", "1"]],{disabled:trail_check(current_user,t) }),{}, {id:"type_select_#{t.id}" ,:class=>"selectpicker show-menu-arrow type-select" ,"data-size" =>"5.5","data-width" =>"100%"} )%>
                  </div>
                </div>
                <div class="col-xs-3">
                  <div class="day">
                    <span>Day</span>
                    <%= select({},{},t.find_available_days(), {:include_blank => "Select a day"}, {id:"day_select_#{t.id}" ,:class=>"selectpicker show-menu-arrow day-select" ,"data-size" =>"5.5","data-width" =>"100%"} )%>
                    <%#= collection_select(:language_ids, Language.all, :id, :language,{}, { :class => "form-control",:id=>"language-select",:style=>"width:100%;" }) %>
                  </div>
                </div>
                <div class="col-xs-5">
                  <div class="time">
                    <span>Time</span>
                    <div id="times-select-<%= t.id %>">
                      <%= select({},{},@times,{:include_blank => "Select day first"}, {id:"times_select_#{t.id}" ,:class=>"selectpicker show-menu-arrow time-select" ,"data-size" =>"5.5","data-width" =>"100%"} )%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn closebtn" data-dismiss="modal">Close</button>
            <%#= x.submit 'Quick Book',:class=>"btn bookteacherbtn" %>
            <button type="button" class="btn bookteacherbtn book_pass_params" data-dismiss="modal" id="book_teacher_click">Quick Book</button>
          </div>
        </div>
      </div>
    </div>
<% end %>
<script>
  $('.teacher-modal').on('shown.bs.modal', function () {
    var teacher_modal = $(this).closest(".teacher-modal")
    var tid = teacher_modal.data("teacher-id");
    var calendar_url = teacher_modal.data("calendar-url");

    $('#calendar-' + tid ).fullCalendar({
      //lulu setting
      buttonIcons: false,
      buttonText: {
        prev: '<  Prev',
        next: 'Next  >'
      },
      header: {
        left: 'prev',
        center: 'title',
        right: 'next'
      },
      axisFormat: 'H:mmA',
      dragOpacity: {
        agenda: .5
      },
      theme: false,
      dragScroll: false,
      contentHeight: 'auto',
      eventColor: '#C73C3C',
      //lulu setting 24小時制 大寫H timeFormat: 'H:mm',
      allDaySlot: false,
      defaultDate: '<%=Time.now.strftime("%Y-%m-%d")%>',
      defaultView: 'agendaWeek',
      ignoreTimezone: false,
      droppable: true,
      eventLimit: true, // allow "more" link when too many events
      eventSources: [
        {
          //teacher events source
          url: calendar_url,
          rendering: 'background'
        }
      ]
    });
    $('.book_pass_params').attr('disabled', true);
  });

  function update_times_select() {
    var teacher_modal = $(this).closest(".teacher-modal");

    var selected = teacher_modal.find(".day-select").find("option:selected").val();
    //var type_selected = teacher_modal.find(".type-select").find("option:selected").val();
    var type = teacher_modal.find(".type-select").find("option:selected").val();

    var tid = teacher_modal.data("teacher-id");

    var userid = <%= current_user.id %>;
    $.ajax({
      type: 'GET',
      dataType: 'script',
      url: "/users/" + userid + "/mytutor",
      data: {
        tid: tid,
        selected: selected,
        type: type
      }
    });
  }
  function check_book_now() {
    var teacher_modal = $(this).closest(".teacher-modal");
    var button = teacher_modal.find(".book_pass_params")
    var day = teacher_modal.find(".day-select").find("option:selected").val();
    if (day == ""  ){
      button.attr('disabled', true);
    }  if( day != ""){
      button.attr('disabled', false);
    }
  }

  $('.type-select').on('change', function(){
    update_times_select.bind(this)();
  });

  $('.day-select').on('change', function(){
    check_book_now.bind(this)();
    update_times_select.bind(this)();

  });

  $('.book_pass_params').click(function(){
    var teacher_modal = $(this).closest(".teacher-modal");
    var selected = teacher_modal.find(".day-select").find("option:selected").val();
    //var type_selected = teacher_modal.find(".type-select").find("option:selected").val();
    var type = teacher_modal.find(".type-select").find("option:selected").val();
    var tid = teacher_modal.data("teacher-id");
    var time = teacher_modal.find("#times_select_"+tid).find("option:selected").val();
    $.ajax({
      type: 'POST',
      dataType: 'script',
      url: "/appointments",
      data: {
        tid: tid,
        selected: selected,
        time: time
      }
    });
    window.location.href = "/users/"+<%= current_user.id %>+"/classes";
  });


  <% UserAvailableSection.where(user_id:current_user).select(:teacher_id).uniq.each do |a|%>
  $("#rateYo-<%= a.teacher_id %>").rateYo({starWidth: "18px", numStars: 5, fullStar: true, readOnly: true, rating: <%= a.teacher.avg_rating %>});
  <% end %>

</script>

app/views/users/mytutor.js.erb
$("#times-select-<%= @teacher.id %>").html("<%=j render :partial=>"times_select", :locals => { :t => @teacher } %>");


$('#times-select-<%= @teacher.id %> .selectpicker').selectpicker();