config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/super', as: 'rails_admin'

  def scheme
    if @env['HTTPS'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SSL'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SCHEME']
      @env['HTTP_X_FORWARDED_SCHEME']
    elsif @env['HTTP_X_FORWARDED_PROTO']
      @env['HTTP_X_FORWARDED_PROTO'].split(',')[0]
    else
      @env["rack.url_scheme"]
    end
  end

  def ssl?
    scheme == 'https'
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :appointments
  end

  post 'pay2go/return'
  post 'pay2go/notify'

  post "/paypal/webhook" => "paypal#webhook"
  post "/paypal/redirect" => "paypal#redirect" # for paypal return

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}
  resources :messages

  resources :users do
    member do
      get :classes
      get :changepassword
      get :remark
      get :editprofile
      get :mytutor
      post :mytutor
    end
    resources :orders do
      member do
        post :checkout_pay2go
        post :checkout_paypal
      end
    end
    resources :available_section, controller: 'user_available_sections'
    member do
      get 'profile'
    end
  end

  resources :teachers do
    member do
      get 'classes' => 'teachers#classes'
      get 'profile' => 'teachers#profile'
      post 'profile' => 'teachers#profile#create'
      get 'calendar' => 'teachers#calendar'
      get 'introduce' => 'teachers#introduce'
      get 'price' => 'teachers#price'
      get 'education' => 'teachers#education'
      get 'youtube' => 'teachers#youtube'
      get 'gathering' => 'teachers#gathering'
    end
    resources :available_section
  end
  get 'apply_teacher_file' => 'teachers#apply_teacher_file'

  resources :appointments do
    resources :evaluations
  end

  resources :student_reservation
  post 'free_trial' =>'student_reservation#free_trial'

  resources :teacher_calendars do
    get 'teacher_available_section' => 'teacher_calendars#teacher_available_section'
    get 'booked_section' => 'teacher_calendars#booked_section'
  end

  get  'scholarship'=> "welcome#scholarship"
  get  'apply_teacher'=> "welcome#apply_teacher"
  get  'teacherwall'=>"welcome#index"
  root 'welcome#mainindex'
  get 'thankyou' => "orders#thankyou"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :find_language, only: :index

  def mainindex
  end

  def index
    if params[:language_id] && params[:week].blank?
      cookies[:lan] = params[:language_id]
      cookies[:week] = nil
      find_language_teacher
    elsif params[:week] && params[:language_id].blank?
      cookies[:lan] = nil
      cookies[:week] = params[:week]
      find_week_teacher

    elsif params[:week] && params[:language_id]
      cookies[:lan] = params[:language_id]
      cookies[:week] = params[:week]
      @teachers = find_language_teacher & find_week_teacher
    elsif params[:price]
      if cookies[:lan].blank? && cookies[:week].blank?
        find_price_teacher
      elsif cookies[:lan] && cookies[:week].blank?
        @teachers = find_language_teacher & find_price_teacher
      elsif cookies[:lan].blank? && cookies[:week]
        @teachers = find_week_teacher & find_price_teacher
      elsif cookies[:lan] && cookies[:week]
        @teachers = find_language_teacher & find_week_teacher & find_price_teacher
      end
      respond_to do |format|
        format.js { render 'teacher' }
      end

    elsif params[:week].blank? && params[:language_id].blank?
      cookies[:lan] = nil
      cookies[:week] = nil
      @teachers = Teacher.all
    end

    # @teachers = @teachers.page(params[:page]).per(10)
    #
    # if @teachers.last_page?
    #    @next_page = nil
    # else
    #    @next_page = @teachers.next_page
    # end
  end

  def apply_teacher
  end

  def scholarship
    @encrypted_data = amazing_crypt("encrypt",current_user.email) if current_user
  end

  private

  def find_language
    params[:language_id] ? @language = Language.find(params[:language_id]).language : @language = "Teacher also know the ...."
  end

  def find_price_teacher
    @teachers = Teacher.where('ten_fee >= ? AND one_fee <= ?', params[:price].first.to_i, params[:price].last.to_i)
  end

  def find_language_teacher
    @teachers = Teacher.includes(:teacher_languageships).where(teacher_languageships: { language_id: cookies[:lan] }).uniq
  end

  def find_week_teacher
    @week = cookies[:week].to_i - 1
    @thedaytime = Time.current.utc.at_beginning_of_week + @week.day
    @thedaytimeend = @thedaytime.end_of_day
    if @thedaytime == Time.current.utc.beginning_of_day
      @thedaytime = Time.current.utc+12.hours
      @thedaytimeend = Time.current.utc.end_of_day
      if @thedaytime >= @thedaytimeend
        @thedaytime = @thedaytimeend
      end
    elsif @thedaytime < Time.current.utc
      @thedaytime +=  7.day
      @thedaytimeend = @thedaytime.end_of_day
    end
    @as = (AvailableSection.where('start > ? AND start < ? AND end > ?', @thedaytime, @thedaytimeend,@thedaytimeend) +
           AvailableSection.where('start < ? AND end > ?', @thedaytime, @thedaytimeend) +
           AvailableSection.where('end > ? AND end < ? AND start < ?', @thedaytime, @thedaytimeend, @thedaytime) +
           AvailableSection.where('start > ? AND end < ?', @thedaytime, @thedaytimeend) ).uniq
    @teacher_id = AvailableSection.where(id: @as).pluck(:teacher_id).uniq
    @teachers = Teacher.where(id: @teacher_id)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def show_week
    week = "All" if params[:week].nil?
    week = "Monday" if  params[:week] == "1"
    week = "Tuesday"if params[:week] == "2"
    week = "Wednesday" if params[:week] == "3"
    week = "Thursday" if params[:week] == "4"
    week = "Friday" if  params[:week] == "5"
    week = "Saturday" if params[:week] == "6"
    week = "Sunday" if params[:week] == "7"
    week
  end

  def show_language
   lan = "All" if params[:language_id].nil?
   lan = Language.find(params[:language_id]).language if params[:language_id].present?
   lan
  end
end

app/views/welcome/_moneyred.html.erb
<% unless current_user %>
    <% if t.ten_fee < t.one_fee %>
      <%= number_to_currency(t.ten_fee,precision: 2 ) %>~<%= number_to_currency(t.one_fee, precision: 2) %>
      USD/Hour
    <% else %>
      <%= number_to_currency(t.one_fee, precision: 2) %>~<%= number_to_currency(t.ten_fee,precision: 2 ) %>
      USD/Hour
    <% end %>
<% else %>
    <% if t.ten_fee < t.one_fee %>
      <%= number_to_currency(t.ten_fee_exchange_to(current_user.currency),precision: 2 ) %>~<%= number_to_currency(t.one_fee_exchange_to(current_user.currency), precision: 2) %>
      <%= current_user.currency %>/Hour
    <% else %>
      <%= number_to_currency(t.one_fee_exchange_to(current_user.currency), precision: 2) %>~<%= number_to_currency(t.ten_fee_exchange_to(current_user.currency),precision: 2 ) %>
      <%= current_user.currency %>/Hour
    <% end %>
<% end %>

app/views/welcome/_teacher.html.erb
<% @teachers.each do |t| %>
    <% if t.check == "checked" %>
        <div class="container scroll">
          <div class="info">
            <div class="row">
              <div class="col-sm-5">
                <div class="youtube-container">
                  <div class="youtube-player-<%= t.id %> youtube-player" data-id="<%= t.youtube_website %>"></div>
                </div>
              </div>
              <div class="col-xs-12 col-sm-7">
                <div class="col-xs-12 clearfix flexmodify">
                  <div class="info-mypic col-md-2 col-xs-3">
                    <%= user_headimage(t.user) %>
                  </div>
                  <%= link_to profile_teacher_path(t), :target => "_blank"  do %>
                      <div class="info-eval col-md-6 col-xs-6">
                        <p><%= User.find(t.user_id).first_name %>
                          <%= User.find(t.user_id).last_name %></p>
                        <div class="index_rating_fix"><div id="rateYo-<%= t.id %>" ></div></div>
                          <span>(<%= Evaluation.where(evaluatable_type: "User", evaluated_id: t.id ).count %>)
                      </div>
                      <div class="trial_button_fix">
                      <div class=" col-xs-2 <%= "green_trial_butoon" if t.trial_fee == 0 %> <%= "red_trial_butoon" if t.trial_fee > 0 %> col-md-push-1 col-md-2">
                        <%= button_to profile_teacher_path(t) do %>
                            <%= "FREE Trial" if t.trial_fee == 0%>
                            <%= t.trial_fee.to_s + " USD Trial" if t.trial_fee > 0 %>
                        <% end %>
                      </div>
                      </div>
                      </div>
                      <div class="col-xs-12 clearfix info-tag">
                        <i class="fa fa-comment-o"></i>
                        <span>Speak:
                        </span>
                        <span>
                          <% t.languages.each do |x| %>
                          <%= x.language %>
                          <% end %>
                        </span><br>
                        <i class="fa fa-globe" aria-hidden="true"></i>
                        <span>From: Taiwan</span>
                        <br>
                        <i class="fa fa-usd"></i>
                        <span>Rate:
                        </span>
                        <span class="moneyred">
                          <%= render partial: 'moneyred', locals: {t: t} %>
                        </span><br>
                      </div>
                      <div class="col-xs-12 info-pro">
                        <p class="teacherwallpa"><%= t.introduction %></p>
                      </div>
                  <% end %>
                  </div>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

<script>
  $(document).ready(function () {
    (function () {
      <% @teachers.each do |t| %>
      var v = document.getElementsByClassName("youtube-player-<%= t.id %>");
      for (var n = 0; n < v.length; n++) {
        var p = document.createElement("div");
        p.innerHTML = labnolThumb(v[n].dataset.id);
        p.onclick = labnolIframe;
        v[n].appendChild(p);
      }
      <% end %>
    })();
    function labnolThumb(id) {
      return '<img class="youtube-thumb" src="//i.ytimg.com/vi/' + id + '/hqdefault.jpg"><div class="play-button"></div>';
    }
    function labnolIframe() {
      var iframe = document.createElement("iframe");
      iframe.setAttribute("src", "//www.youtube.com/embed/" + this.parentNode.dataset.id + "?autoplay=1&autohide=2&border=0&wmode=opaque&enablejsapi=1&showinfo=0");
      iframe.setAttribute("frameborder", "0");
      iframe.setAttribute("id", "youtube-iframe");
      this.parentNode.replaceChild(iframe, this);
    }

    <% @teachers.each do |t|%>
    $("#rateYo-<%= t.id %>").rateYo({starWidth: "18px", numStars: 5, fullStar: true, readOnly: true, rating: <%= t.avg_rating %>});

    <% end %>
  });
</script>

app/views/welcome/apply_teacher.html.erb
<section class="header">
  <div class="content-apply">
    <h2>申請華語教師 在家教中文</h2>
    <h4>在家教華語 每週增加上萬元收入</h4>
    <% if current_user %>
        <%= link_to "立即申請" ,apply_teacher_file_path %>
    <% else %>
        <%= link_to "立即申請" ,new_user_registration_path %>
    <% end %>
  </div>
</section>
<section class="reason">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-xs-12 col-md-offset-3">
        <h3>加入 AmazingTutor 的理由</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-xs-12">
        <%= image_tag("money_bag_filled.png") %>
        <h4>賺取額外收入</h4>
        <h5>作為一名Amazingtutor教師您可以隨意設定自己的價格。線上授課即可輕鬆賺取上萬塊台幣。</h5>
      </div>
      <div class="col-md-4 col-xs-12">
        <%= image_tag("bullish_filled.png") %>
        <h4>建立個人品牌</h4>
        <h5>建立線上教學聲譽，展示教學品質、與您的教學經驗背景，使用該聲譽讓更多學員找到你。</h5>
      </div>
      <div class="col-md-4 col-xs-12">
        <%= image_tag("thursday_copy.png") %>
        <h4>彈性教課</h4>
        <h5>您的教學時間由您自己決定！學生僅可以在你安排的可用時間內預約您的課時。</h5>
      </div>
    </div>
  </div>
</section>

<section class="apply">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-xs-12 col-md-offset-3">
        <h3>立即申請</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-xs-12">
        <%= image_tag("1462287713_finance-46.png") %>
        <h4>線上申請 快速加入</h4>
        <h5>現在立即30秒完成註冊 馬上線上開始教課！</h5>
      </div>
      <div class="col-md-5 col-xs-12">
        <%= image_tag("1462287740_finance-60.png") %>
        <h4>免加入費用 週週加薪上萬塊</h4>
        <h5>無需任何額外費用，超高賺錢效率讓你每週為自己輕鬆加薪！</h5>
      </div>
    </div>
  </div>
</section>

<!--<section class="apply_input">-->
<!--<div class="container">-->
<!--<div class="row">-->
<!--<div class="col-md-4 col-md-offset-1 col-xs-12">-->
<!--<h4>立即開始教課</h4>-->
<!--<h5>留下你的聯絡資料，我們服務將在近期正式上線，屆時您將可以開始在家教學的旅程，輕鬆開始在家工作的新生活！趕緊加入我們吧！</h5>-->
<!--</div>-->
<!--<div class="col-md-5 col-xs-12 col-md-push-1">-->
<!--<input type="text" placeholder="   Name" >-->
<!--<input type="text" placeholder="   Email">-->
<!--<input type="text" placeholder="   Phone">-->
<!--<button>立即申請</button>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</section>-->
<section class="teacherQA">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3>教師Q&A</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>1.我需要的教學經驗？</h4>
        <h5>我們會建議您有相關的教學經驗，但您依然可以提出申請，我們會依照您的申請內容判定是否能成為我們的教師。</h5>
      </div>
      <div class="col-md-6">
        <h4>4.我該如何申請任教於Amazingtutor？</h4>
        <h5>在Amazingtutor 提交申請表，並等待審核。</h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>2.我是否需要教師資格證？</h4>
        <h5>如果有正式的教師證可以大大的加分並增加錄取的機會，但不是必須的。</h5>
      </div>
      <div class="col-md-6">
        <h4>5.我可以申請教導不是目前Amazingtutor列出的語言？</h4>
        <h5>目前的計畫是只有中文教學，您可以提出申請教授其他語言，我們團隊收到後會進行評估。</h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>3.我需要成為是母語者嗎？</h4>
        <h5>通常情況下，在 Amazingtutor 最好的老師是那些教他們的母語經驗。然而，我們有時會有中文能力極佳的非母語者成為教師。</h5>
      </div>
      <div class="col-md-6">
        <h4>6.我什麼時候能收到 Amazingtutor 的通知？</h4>
        <h5>您的申請我們會在二週內回覆，不管申請成功或是失敗，由於申請人數眾多，我們只通知合格申請者。如果您遲遲未收到我們的信件，歡迎二周後再次申請。</h5>
      </div>
    </div>
  </div>
</section>

<section class="payment_teacher">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3>費用支付</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>1.多久付款一次？</h4>
        <h5>每月十號會寄出您的教師費用，並在每月十五號撥款。
        </h5>
      </div>
      <div class="col-md-6">
        <h4>2. 我該如何找學生？</h4>
        <h5>Amazingtutor專注打造更棒的線上中文學習，取得更多潛力中文學生。你只需要專心累積自己的授課評價以及紀錄，就可以讓更多想學中文的學生可以在這平台上找到你!
        </h5>
      </div>
    </div>
  </div>
</section>
<section class="techniqe">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3>需要技術</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>1. 我需要做什麼來教上Amazingtutor？</h4>
        <h5>教師需要一個非常可靠的網路環境，一個正常運作的麥克風和網絡攝像頭。
        </h5>
      </div>
      <div class="col-md-6">
        <h4>2. 我使用的是什麼即時影音科技？</h4>
        <h5>在Amazingtutor所有的教學是透過google hangouts 進行視頻上課（不要擔心 如果你是新來的Hangouts，我們可以向你保證它很容易上手且易於使用）。
        </h5>
      </div>
    </div>
    <% if current_user %>
        <%= link_to "立即申請" ,apply_teacher_file_path,class:"apply_now" %>
    <% else %>
        <%= link_to "立即申請" ,new_user_registration_path,class:"apply_now" %>
    <% end %>
  </div>
</section>

app/views/welcome/index.html.erb
<div class="jumbotron jumbotron-modify">
  <div class="container">
    <div class="row"><div class="col-xs-7">
    <h2>Find a Chinese Tutor</h2>
    <p>Amazingtutor brings you perfect and self-paced access to learn Chinese. Find enthusiastic and excellent teachers to complete your learning experience.</p>
    </div></div>
  </div>
</div>
<div class="container-fluid search">
  <div class="row-fluid">
    <div class="container">
      <div class="col-sm-4 col-md-4">
        <p>Tutor's Sub-languages</p>
        <div class="dropdown dropdown-language">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownlanguage" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= @language %>
            <span class="caret dropdown-language-span"></span>
          </button>
          <ul class="dropdown-menu dropdown-language-menu" aria-labelledby="dropdownMenu1">
            <% if params[:week] %>
                <li><%= link_to "All", teacherwall_path(:week=>params[:week] ) %></li>
                <% Language.all.each do |l| %>
                    <li><%= link_to l.language, teacherwall_path( :language_id => l.id,:week=>params[:week]  ) %></li>
                <% end %>
            <% else %>
                <li><%= link_to "All", teacherwall_path %></li>
                <% Language.all.each do |l| %>
                    <li><%= link_to l.language, teacherwall_path( :language_id => l.id  ) %></li>
                <% end %>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-sm-4 col-md-4">
        <p>Availability</p>
        <div class="dropdown dropdown-language">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdowntime" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Choose time you want....
            <span class="caret dropdown-language-span"></span>
          </button>
          <ul class="dropdown-menu dropdown-language-menu" aria-labelledby="dropdownMenu1">
            <% if params[:language_id ]  %>
                <li><%= link_to "All", teacherwall_path(:language_id=> params[:language_id]) %></li>
                <li><%= link_to "Monday", teacherwall_path( :week=> 1 ,:language_id=> params[:language_id]) %></li>
                <li><%= link_to "Tuesday", teacherwall_path( :week=>2 ,:language_id=> params[:language_id] ) %></li>
                <li><%= link_to "Wednesday", teacherwall_path( :week=> 3,:language_id=> params[:language_id] ) %></li>
                <li><%= link_to "Thursday", teacherwall_path( :week=> 4,:language_id=> params[:language_id] ) %></li>
                <li><%= link_to "Friday", teacherwall_path( :week=> 5,:language_id=> params[:language_id] ) %></li>
                <li><%= link_to "Saturday", teacherwall_path( :week=> 6,:language_id=> params[:language_id] ) %></li>
                <li><%= link_to "Sunday", teacherwall_path( :week=> 7,:language_id=> params[:language_id] ) %></li>
            <% else %>
                <li><%= link_to "All", teacherwall_path  %></li>
                <li><%= link_to "Monday", teacherwall_path( :week=> 1 ) %></li>
                <li><%= link_to "Tuesday", teacherwall_path( :week=>2  ) %></li>
                <li><%= link_to "Wednesday", teacherwall_path( :week=> 3 ) %></li>
                <li><%= link_to "Thursday", teacherwall_path( :week=> 4 ) %></li>
                <li><%= link_to "Friday", teacherwall_path( :week=> 5 ) %></li>
                <li><%= link_to "Saturday", teacherwall_path( :week=> 6 ) %></li>
                <li><%= link_to "Sunday", teacherwall_path( :week=> 7 ) %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-md-4">
        <p>Price US dollars</p>
        <input id="priceslide" type="text" class="priceslide" value="" data-slider-min="1" data-slider-max="100" data-slider-step="1" style="width:100% !important"/>
      </div>
    </div>
  </div>
</div>
<div id="teachers">
  <%= render "teacher", :locals => {:teachers => @teachers} %>
</div>
<script>

  $(document).ready(function () {
    $("#js-example-basic-single").select2();
    $('#priceslide').slider({value: [1,100]}).on('slideStop', function (ev) {

      var price = $('#priceslide').data('slider').getValue();

      $.ajax({
        url: "/teacherwall",
        contentType: false,
        type: 'GET',
        data: {
          price: price
        }
      });
    });

    var language = '<%= show_language %>'+ '<span class="caret dropdown-language-span"></span>';
    var time = '<%= show_week %>'+ '<span class="caret dropdown-language-span"></span>';
    $('#dropdownlanguage').html(language);
    $('#dropdowntime').html(time);
  });
</script>

app/views/welcome/index.js.erb
var html = "<%= j( render :partial => "list" ) %>";

$("#teachers-list").append(html);

<% if @next_page %>
  $("#load-more").attr("href", "<%= teacher_path(@teacher, :page => @next_page) %>")
<% else %>
  $("#load-more").remove();
<% end %>

app/views/welcome/mainindex.html.erb
<section class="main-head">
  <div class="container-fluid main_head_content">
    <div class="row">
      <div class="col-md-4 col-md-push-1 main_head_link col-sm-6 col-sm-push-1">
        <h1>Learn to speak Chinese in 30 minutes</h1>
        <h3>one-on-one mandarin lessons from native speakers</h3>
        <% if current_user %>
            <%= link_to "Get Start Now",teacherwall_path %>
        <% else %>
            <%= link_to "Get Start Now",new_user_registration_path %>
        <% end %>
      </div>
    </div>
  </div>
</section>
<section class="get_start_down">
  <% if current_user %>
      <%= link_to "Get Start Now",teacherwall_path %>
  <% else %>
      <%= link_to "Get Start Now",new_user_registration_path %>
  <% end %>
</section>
<section class="teacherwall">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>200+ Professional Teachers</h1>
        <h3>All of our teachers have a certificate, degree or experience in Chinese teaching.</h3>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-xs-10 col-xs-push-1">
        <div class="row-fluid">
          <div class="col-md-4 col-xs-6 teacherpic">
            <%= link_to profile_teacher_path(273) do %>
                <%= image_tag("6.jpg") %>
            <% end %>
          </div>
          <div class="col-md-4 col-xs-6 teacherpic">
            <%= link_to profile_teacher_path(279) do %>
                <%= image_tag("2.jpg") %>
            <% end %>
          </div>
          <div class="col-md-4 col-xs-6 teacherpic">
            <%= link_to profile_teacher_path(292) do %>
                <%= image_tag("3.jpg") %>
            <% end %>
          </div>
          <div class="col-md-4 col-xs-6 teacherpic">
            <%= link_to profile_teacher_path(270) do %>
                <%= image_tag("1.jpg") %>
            <% end %>
          </div>
          <div class="col-md-4 col-xs-6 teacherpic">
            <%= link_to profile_teacher_path(274) do %>
                <%= image_tag("5.jpg") %>
            <% end %>
          </div>
          <div class="col-md-4 col-xs-6 teacherpic">
            <%= link_to profile_teacher_path(277) do %>
                <%= image_tag("4.jpg") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="golesson">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>How Do I Schedule a Lesson?</h1>
        <h3>Easy to have an online private tutor class via AmazingTutor!</h3>
      </div>
    </div>
    <div class="row">

      <div class="col-md-4 lesson_pic"><%= image_tag("43.png") %>
        <h3>Choose a Tutor</h3>
        <h4>Watch our Tutor’s profile videos and read reviews from previous students.</h4>
      </div>

      <div class="col-md-4 lesson_pic"><%= image_tag("42.png") %>
        <h3>Book a Lesson</h3>
        <h4>Choose a time that fits your schedule the best.</h4>
      </div>
      <div class="col-md-4 lesson_pic"><%= image_tag("41.png") %>
        <h3>Connect</h3>
        <h4>Meet our Tutor face-to-face on Amazingtutor!</h4>
      </div>

    </div>
  </div>
  </div>
</section>
<section class="whyme">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Why AmazingTutor?</h1>
        <h3>We created the best environment to overcome the limits of traditional language schools.</h3>
      </div>
    </div>
    <div class="row ">
      <div class="col-sm-4 ">
        <div class="whyme_content"><%= image_tag("21.jpg") %>
          <h3>Culture Sharing</h3>
          <h4>language is all about the culture, so we share what’s happening here and things that will never bored you!</h4>
        </div>
      </div>
      <div class="col-sm-4 ">
        <div class="whyme_content"><%= image_tag("22.jpg") %>
          <h3>Realtime Correction</h3>
          <h4>Pronounce like a native speaker by chatting with us</h4>
        </div>
      </div>
      <div class="col-sm-4 ">
        <div class="whyme_content"><%= image_tag("23.jpg") %>
          <h3>Flexibility</h3>
          <h4>Where to learn or when to learn? You decide and We'll follow!</h4>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="main_footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 col-md-push-1 text-center ">
        <div class="main_head_content">
          <h1>Our Ambition</h1>
          <h3>Create the best online Chineses learning experience for all!</h3>
          <% if current_user %>
              <%= link_to "Get Start Now",teacherwall_path %>
          <% else %>
              <%= link_to "Get Start Now",new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="get_start_down">
  <% if current_user %>
      <%= link_to "Get Start Now",teacherwall_path %>
  <% else %>
      <%= link_to "Get Start Now",new_user_registration_path %>
  <% end %>
</section>

app/views/welcome/teacher.js.erb
$("#teachers").html("<%= j render( :partial => "teacher", :locals => { :teachers => @teachers } ) %>")