config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/super', as: 'rails_admin'

  def scheme
    if @env['HTTPS'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SSL'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SCHEME']
      @env['HTTP_X_FORWARDED_SCHEME']
    elsif @env['HTTP_X_FORWARDED_PROTO']
      @env['HTTP_X_FORWARDED_PROTO'].split(',')[0]
    else
      @env["rack.url_scheme"]
    end
  end

  def ssl?
    scheme == 'https'
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :appointments
  end

  post 'pay2go/return'
  post 'pay2go/notify'

  post "/paypal/webhook" => "paypal#webhook"
  post "/paypal/redirect" => "paypal#redirect" # for paypal return

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}
  resources :messages

  resources :users do
    member do
      get :classes
      get :changepassword
      get :remark
      get :editprofile
      get :mytutor
      post :mytutor
    end
    resources :orders do
      member do
        post :checkout_pay2go
        post :checkout_paypal
      end
    end
    resources :available_section, controller: 'user_available_sections'
    member do
      get 'profile'
    end
  end

  resources :teachers do
    member do
      get 'classes' => 'teachers#classes'
      get 'profile' => 'teachers#profile'
      post 'profile' => 'teachers#profile#create'
      get 'calendar' => 'teachers#calendar'
      get 'introduce' => 'teachers#introduce'
      get 'price' => 'teachers#price'
      get 'education' => 'teachers#education'
      get 'youtube' => 'teachers#youtube'
      get 'gathering' => 'teachers#gathering'
    end
    resources :available_section
  end
  get 'apply_teacher_file' => 'teachers#apply_teacher_file'

  resources :appointments do
    resources :evaluations
  end

  resources :student_reservation
  post 'free_trial' =>'student_reservation#free_trial'

  resources :teacher_calendars do
    get 'teacher_available_section' => 'teacher_calendars#teacher_available_section'
    get 'booked_section' => 'teacher_calendars#booked_section'
  end

  get  'scholarship'=> "welcome#scholarship"
  get  'apply_teacher'=> "welcome#apply_teacher"
  get  'teacherwall'=>"welcome#index"
  root 'welcome#mainindex'
  get 'thankyou' => "orders#thankyou"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  has_many :teacher_languageships
  has_many :languages, through: :teacher_languageships
  has_many :available_sections
  has_many :appointments
  has_many :evaluations, as: :evaluatable
  has_many :experiences
  has_many :certificates
  has_many :educations
  has_many :orders
  has_many :appointments
  accepts_nested_attributes_for :teacher_languageships, allow_destroy: true
  accepts_nested_attributes_for :languages, allow_destroy: true
  accepts_nested_attributes_for :experiences, allow_destroy: true
  accepts_nested_attributes_for :certificates, allow_destroy: true
  accepts_nested_attributes_for :educations, allow_destroy: true

  def uniq_language
    array = []
    params[:teacher][:languages_attributes].map { |x| array << x[:language] }
    array.uniq
  end

  def youtube_website
    youtube.split("=").last
  end

  def one_fee_exchange_to(iso_to)

    Money.new(one_fee*100, "USD").exchange_to(iso_to)
  end

  def five_fee_exchange_to(iso_to)
    Money.new(five_fee*100, "USD").exchange_to(iso_to)
  end

  def ten_fee_exchange_to(iso_to)
    Money.new(ten_fee*100, "USD").exchange_to(iso_to)
  end

  # def check_fee(fee,session)
  #   fee = (fee.to_i)/(session.to_i)
  #
  #   if fee == self.one_fee || fee == self.five_fee || fee == self.ten_fee
  #     return true
  #   else
  #     return false
  #   end
  # end

  # def hangouts_url
  #   if self.hangouts_url.blank?

  #     charset = (0...4).map { ('a'..'z').to_a[ rand(26)] }.join
  #     url =  "https://talkgadget.google.com/hangouts/_/i"+charset+"m5jzffaheagjkaa5wzj7y2?hl=zh-TW"
  #     self.hangouts_url = url
  #   end
  # end

  def appointment_check(start_time, end_time)
    self.appointments.where("(start >= ? and end <= ?) or (start >= ?  and start < ?) or (end > ?  and end <= ?) or (start < ? and end > ?)",
                            start_time, end_time,
                            start_time, end_time,
                            start_time, end_time,
                            start_time, end_time).exists?
  end

  def find_available_days
    @days = []
    self.available_sections.each do |available_section|
      @start = available_section.start
      @end = available_section.end
      for i in 0..((@end - @start)/1.day).to_i
        @days << @start + i.days
      end
    end
    @days.select{|x| x>= Time.current.in_time_zone + 1.hours }.map{|x|x.to_date}.uniq.sort
    # @available_section_times.uniq.sort.select{|x| [x[0],x[1]] if x[0]>= Time.current.in_time_zone+12.hours }
  end

  def find_available_times(pickedday= Time.current.in_time_zone,section=2)
    @available_section_times = []
    @pickedday = pickedday.to_date.in_time_zone
    @pickedday_start = @pickedday.beginning_of_day
    @pickedday_end = @pickedday.end_of_day
    # type 要輸入1 or 2 試上 或正式課
    available_sections.each do |available_section|
      for i in 0..((available_section.end - available_section.start) / 24.hours).to_i+1
        @forday = available_section.start.to_date + i.days
        if @forday == @pickedday.to_date
          if available_section.start >= @pickedday_start && available_section.start < @pickedday_end && available_section.end > @pickedday_end
            block = (((@pickedday_end + 1) - available_section.start) / 30.minute).to_i - 1
            x = available_section.start
          end
          if available_section.start <  @pickedday_start && available_section.end > @pickedday_end
            block = (((@pickedday_end + 1) - @pickedday_start) / 30.minute).to_i - 1
            x = @pickedday_start
          end

          if available_section.end > @pickedday_start && available_section.end <= @pickedday_end && available_section.start < @pickedday_start
            block = ((available_section.end - @pickedday_start) / 30.minute).to_i - 1
            x = @pickedday_start
          end
          if available_section.start >= @pickedday_start && available_section.end < @pickedday_end
            block = ((available_section.end - available_section.start) / 30.minute).to_i - 1
            x = available_section.start
          end
          unless block.nil?
            for i in 0..block
              @available_section_times << [ x , x + (section* 30.minute)]
              x += 30.minute
            end
          end
          # if @available_section_times.present?
          # @available_section_times.pop if @available_section_times.last.last > available_section.end
          #   end
          @available_section_times.pop if section == 2 && block != nil
        end
      end
    end
    @available_section_times.uniq.select{|x| x unless self.appointment_check(x[0], x[1])}.sort.select{|x| x[0]>= Time.current.in_time_zone + 1.hours}.map{|x| x[0].strftime('%R %p')+" - "+x[1].strftime('%R %p') }
  end
  # @available_section_times.uniq.select{|x| x unless self.appointment_check(x[0], x[1])}.sort.select{|x| x[0]>= Time.current.in_time_zone+12.hours }.map{|x| x[0].strftime('%r')+" - "+x[1].strftime('%r') }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :teacher_authority, except: [:profile, :index , :apply_teacher_file,:update]
  before_action :get_teacher, except: :profile
  # before_action :get_hangouts_url

  # 只有user裡面的author得值要等於teacher才可以進來 但大家都有第一次可能進來沒有teacher
  # 所以全部要before_action先建好teacher 如果已經有了就用已經有的

  def index
    @teachers = Teacher.all
    @appointments = Appointment.all
    @evaluations = Evaluation.all
  end

  def introduce
    @teacher.teacher_languageships.new if @teacher.teacher_languageships.empty?
    render layout: 'welcome'
  end

  def calendar
  end

  def classes
    @appointments = @teacher.appointments
  end

  def profile
    @teacher = Teacher.find(params[:id])
    redirect_to root_path if @teacher.check != 'checked'
    @evaluations = Evaluation.all.where(evaluatable_type: 'User', evaluated_id: @teacher)
    @teacher = Teacher.find_by_id(params[:id])
    unless current_user.nil?
      @user_available_sections = current_user.user_available_sections.find_by_teacher_id(params[:id])
    end
  end

  def price
  end

  def gathering
    @gathering = @teacher.gathering_way
  end

  def education
    @language = @teacher.educations.build if @teacher.educations.empty?
    @language = @teacher.experiences.build if @teacher.experiences.empty?
    @language = @teacher.certificates.build if @teacher.certificates.empty?
  end

  def youtube
  end

  def hangouts_url
  end

  def apply_teacher_file
  end


  def update
    teacher_authority_without_authority
    if params[:teacher][:youtube]
      if params[:teacher][:youtube].include?('https://www.youtube.com/watch')
        @teacher.youtube = params[:teacher][:youtube]
        @teacher.save
        # redirect_to :back
        flash[:alert] = 'Save success'
        redirect_to :back
      else
        flash[:alert] = 'Save fail because video not from Youtube'
        redirect_to :back
      end
    else
      @teacher.update(teacher_params)
      if @teacher.save
        redirect_to :back
        flash[:alert] = 'Save success'
      else
        flash[:alert] = 'Save fail ! Maybe some inputs empty.'
        redirect_to :back
      end
    end
  end

  private

  def get_teacher
    @teacher = if current_user.teacher
                 current_user.teacher
               else
                 current_user.create_teacher
               end
  end
  #
  # def get_hangouts_url
  #   if current_user.teacher.hangouts_url.blank?
  #     charset = ""
  #     url = ""
  #     charset = (0...9).map { ('a'..'z').to_a[ rand(26)] }.join
  #     url =  "https://talkgadget.google.com/hangouts/_/n"+charset+"aelp4l25okzw3tw4e?hl=en-US"
  #     current_user.teacher.hangouts_url = url
  #     current_user.teacher.save
  #   end
  # end

  def teacher_authority_without_authority
    @teacher = Teacher.find(params[:id])
    if current_user.nil? || current_user.try(:teacher).id != @teacher.id
      redirect_to root_path
    end
  end

  def teacher_authority
    @teacher = Teacher.find(params[:id])
     if current_user.nil? || current_user.authority != 'teacher' || current_user.try(:teacher).id != @teacher.id
       redirect_to root_path
     end
  end

  def teacher_params
    params.require(:teacher).permit(:user_id, :youtube, :introduction, :trial_fee,
                                    :one_fee, :five_fee, :ten_fee, :gathering_way,
                                    language_ids: [],
                                    languages_attributes: [:language, :_destroy, :id],
                                    experiences_attributes: [:company_name, :description, :_destroy, :id,:start,:end],
                                    educations_attributes: [:school, :major, :_destroy, :id,:start,:end],
                                    certificates_attributes: [:name, :score, :_destroy, :id])
  end
end

app/views/teachers/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-head">
    <%= link_to "課程相關" %>
  </div>
  <div class="sidebar-big <%= "current_tab" if current_page?(classes_teacher_path(current_user.teacher)) %>">
    <%= link_to "課程清單" ,classes_teacher_path(current_user.teacher)%>
  </div>
  <div class="sidebar-big <%= "current_tab" if current_page?(calendar_teacher_path(current_user.teacher)) %>">
    <%= link_to "授課時間" ,calendar_teacher_path(current_user.teacher)%>
  </div>
  <div class="sidebar-big <%= "current_tab" if current_page?(price_teacher_path(current_user.teacher)) %>">
    <%= link_to "授課價格",price_teacher_path(current_user.teacher)%>
  </div>
  <div class="sidebar-big sidebar-bottom <%= "current_tab" if current_page?(gathering_teacher_path(current_user.teacher)) %>">
    <%= link_to "收款設定",gathering_teacher_path(current_user.teacher)%>
  </div>
</div>
<div class="sidebar">
  <div class="sidebar-head ">
    <%= link_to "資訊設定"%>
  </div>
  <div class="sidebar-big <%= "current_tab" if current_page?(introduce_teacher_path(current_user.teacher)) %>">
    <%= link_to "基本資料",introduce_teacher_path(current_user.teacher)%>
  </div>
  <div class="sidebar-big <%= "current_tab" if current_page?(education_teacher_path(current_user.teacher)) %>">
    <%= link_to "教學經驗",education_teacher_path(current_user.teacher)%>
  </div>
  <div class="sidebar-big  sidebar-bottom <%= "current_tab" if current_page?(youtube_teacher_path(current_user.teacher)) %>">
    <%= link_to "介紹影片",youtube_teacher_path(current_user.teacher)%>
  </div>
</div>

app/views/teachers/apply_teacher_file.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-push-2">
      <div class="public-content form-group">
        <%= form_for @teacher do |f| %>
            <div class="public-head">
              <h4>基本資料</h4>
            </div>
            <div class="alert alert-success">
              <%= flash[:alert]  %>
            </div>
            <div class="input-group clearfix language-select-fix">

              <label for="#your-input" class="pull-left ">第二外語</label>
              <%= f.collection_select(:language_ids, Language.all, :id, :language,{}, {:multiple => true, :class => "form-control",:id=>"language-select",:style=>"width:80%;" }) %>
            </div>
            <h6>小提醒：如果您會其他外語歡迎填寫，這樣對學員來說會格外親切
            </h6>
            <hr>
            <div class="input-group clearfix intro-textarea-fix">
              <%= f.label :introduction, "自我介紹" %>
              <%= f.text_area :introduction, :class => "form-control" %>
            </div>
            <hr>
            <div class="public-note">
              <h5>小提醒：</h5>
              <h6>小提醒：大部分的學員對於老師的教學方式、教學背景、已經經歷 會有濃厚的興趣，趕緊寫下你的寶貴經驗吧!</h6>
            </div>
            </div>
            <div class="public-save">
              <%= f.submit 'SAVE', :class => "btn" %>
            </div>
        <% end %>
        </div>
  </div>
</div>

<div class="container p_display_inline">
  <div class="row">
    <div class="col-md-8 col-md-push-2">
      <div class="public-content">
        <div class="public-head">
          <h4>教學經驗</h4>
        </div>
        <div class="alert alert-success">
          <%= flash[:alert]  %>
        </div>
        <div class="public-note">
          <h5>小提醒：請使用英文填寫，如工作經歷跟語言教學有關，會更吸引學員的目光唷!</h5>
        </div>
        <hr class="education_hr">

        <%= nested_form_for @teacher do |f| %>
            <h5 class="add_nested_fix">證照執照</h5>

            <%= f.fields_for :certificates do |ff| %>
                <%= ff.link_to_remove :class=> "removetask" do %>
                    <span class="moneyred closexx">&times;</span>
                <% end %>
                <div class="input-group clearfix">
                  <%= ff.label :name, "證照名稱" %>
                  <%= ff.text_field :name, :class => "form-control"  %>
                </div>
                <div class="input-group clearfix">
                  <%= ff.label :score, "證照分數" %>
                  <%= ff.text_field :score , {:class => "form-control " , required: true }%>
                </div>

            <% end %>
            <%= f.link_to_add :certificates ,:class=>"addtask moneyred" do%>新增證照<% end %>

            <hr>
            <h5 class="add_nested_fix">學歷背景</h5>
            <%= f.fields_for :educations do |ff| %>
                <%= ff.link_to_remove :class=> "removetask" do%>
                    <span class="moneyred closexx">&times;</span>
                <% end %>
                <div class="input-group clearfix">
                  <%= ff.label :start, "開始時間" %>
                  <%= ff.text_field :start, "data-provide" => 'datepicker',:class => "form-control "  %>
                </div>
                <div class="input-group clearfix">
                  <%= ff.label :end, "結束時間" %>
                  <%= ff.text_field :end, "data-provide" => 'datepicker',:class => "form-control "  %>
                </div>

                <div class="input-group clearfix">
                  <%= ff.label :school, "學校名稱" %>
                  <%= ff.text_field :school, :class => "form-control " %>
                </div>
                <div class="input-group clearfix">
                  <%= ff.label :major, "科系全名" %>
                  <%= ff.text_field :major, :class => "form-control " %>
                </div>

            <% end %>
            <p><%= f.link_to_add :educations ,:class=>"addtask moneyred" do%>新增教育背景<% end %></p>
            <hr>

            <h5 class="add_nested_fix">工作經驗</h5>
            <%= f.fields_for :experiences do |ff| %>
                <%= ff.link_to_remove :class=> "removetask" do%>
                    <span class="moneyred closexx">&times;</span>
                <% end %>
                <div class="input-group clearfix ">
                  <%= ff.label :start, "開始時間" %>
                  <%= ff.text_field :start, "data-provide" => 'datepicker',:class => "form-control "  %>
                </div>
                <div class="input-group clearfix">
                  <%= ff.label :end, "結束時間" %>
                  <%= ff.text_field :end, "data-provide" => 'datepicker',:class => "form-control "  %>
                </div>
                <div class="input-group clearfix">
                  <%= ff.label :company_name, "單位名稱" %>
                  <%= ff.text_field :company_name, :class => "form-control " %>
                </div>
                <div class="input-group clearfix">
                  <%= ff.label :description, "服務內容" %>
                  <%= ff.text_area :description, :class => "form-control " %>
                </div>

            <% end %>
            <p><%= f.link_to_add :experiences ,:class=>"addtask moneyred" do%>新增工作經驗<% end %></p>

            <hr>

            </div>
            <div class="public-save">
              <%= f.submit 'SAVE', :class => "btn" %>
            </div>
        <% end %>
        </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-push-2">
      <div class="public-content youtube-fix">
        <div class="public-head">
          <h4>介紹影片</h4>
        </div>
        <h5>個人短片簡介</h5>
        <div class="container-fluid">
          <div class="alert alert-success">
            <%= flash[:alert]  %>
          </div>
          <%= form_for @teacher do |f| %>
              <iframe src="<%= youtube_website %>?playlist=&version=3&controls=0&fs=0&rel=0&showinfo=0&iv_load_policy=3&theme=light" frameborder="0" allowfullscreen></iframe>
              <div class="row">
                <div class="col-xs-3">
                  <h5>Youtube 連結</h5>
                </div>
                <div class="col-xs-9"><%= f.text_field :youtube, :placeholder => "https://www.youtube.com/watch?xxxxxxxxx", :class => "form-control" %>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-3">
                  <h5>短片檢查列表</h5>
                </div>
                <div class="col-xs-9">
                  <h6>・我們喜歡特寫，但建議您坐在離網路攝影機有一臂之遙的位置。</h6>
                  <h6>・您只有3分鐘的時間，所以盡量言簡意賅。</h6>
                  <h6>・盡量讓光線從前方照過來，而不是從後方。</h6>
                  <h6>・眼望鏡頭，製造情感交流。</h6>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-3">
                  <h5>教師專業介紹</h5>
                </div>
                <div class="col-xs-9">
                  <h6>・我們喜歡聽到您來自哪裡、教育背景、以及教學經驗。</h6>
                  <h6>・除了經歷外您會透過什麼樣的方式來給學員教學體驗？</h6>
                  <h6>・我們喜歡跟您的興趣以及愛好有所連結。</h6>
                </div>
              </div>
              </div>
              </div>
              <div class="public-save">
                <%= f.submit 'SAVE', :class => "btn" %>
              </div>
          <% end %>
          </div>
  </div>
</div>


<script>
  $("#language-select").select2({placeholder: "Select a language"});
  $(document).on('nested:fieldAdded', function(event){
    // this field was just inserted into your form
    var field = event.field;
    // it's a jQuery object already! Now you can find date input
    var dateField = field.find('.date');
    // and activate datepicker on it
    dateField.datepicker();
  })
</script>

app/views/teachers/calendar.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 teacher-sidebar-fix">
      <%= render "sidebar" %>
    </div>
    <div class="col-md-8 col-md-push-4">
      <div class="row calendar-content">
        <div class="public-head">
          <h4>授課日曆</h4>
        </div>
        <div class="col-xs-12" id='calendar'>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
      //lulu setting
      buttonIcons: false,
      buttonText: {
        prev: '<  Prev',
        next: 'Next  >'
      },
      header: {
        left: 'prev',
        center: 'title',
        right: 'next'
      },
      axisFormat: 'H:mmA',
      dragOpacity: {
        agenda: .5
      },
      theme: false,
      contentHeight: 'auto',
      eventColor: '#FF5F5F',
      //lulu setting

      //24小時制 大寫H timeFormat: 'h:mm', 移除allDay的欄位
      allDaySlot: false,
      defaultDate: '<%=Time.current.strftime("%Y-%m-%d")%>',
      defaultView: 'agendaWeek',
      eventBorderColor: '#FF5F5F',
      backgroundColor: '#FF5F5F',
      dragScroll: false,
      selectable: true,
      selectHelper: true,
      select: function (start, end) {
        var c = confirm("是否設定可預約時段？\n如果選擇已預約課程的區域內則為刪除.\n刪除內已有學生預約則無法刪除")
        var eventData;
        if (c) {
          //        做一個ajax
          $.ajax({
            url: '<%= teacher_calendars_path %>.json',
            data: {
              start: start.format(),
              end: end.format()
            },
            beforeSend: function (xhr) {
              xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
            },
            type: "POST",
            dataType: 'text',
            success: function (msg) {
              //                var events = JSON.parse(msg);                eventData = {                  start: events.start,                  end: events.end,                  backgroundColor: 'blue',                  rendering:
              // 'background',                };                $('#calendar').fullCalendar('renderEvent', eventData, true); // stick? = true
              $('#calendar').fullCalendar('refetchEvents')
            },

            error: function (xhr, ajaxOptions, thrownError) {
              alert(xhr.status);
              alert(thrownError);
            }
          });
        }
        $('#calendar').fullCalendar('unselect');
      },

      eventLimit: true, // allow "more" link when too many events
      eventSources: [
        {
          url: '<%= teacher_calendar_teacher_available_section_path(@teacher.id)%>'
        }
      ]

    });

  });
</script>

app/views/teachers/classes.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= render "sidebar" %>
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-xs-12">
          <div class="mytutor-sort teacher_sort">
            <div class="dropdown dropdown-language selsct_scheduled">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Choose class status....
                <span class="caret dropdown-language-span"></span>
              </button>
              <ul class="dropdown-menu dropdown-language-menu" aria-labelledby="dropdownMenu1">
                <li><%= link_to "All", classes_teacher_path %></li>
                <li><%= link_to "Scheduled", classes_teacher_path( :classes=> 2 ) %></li>
                <li><%= link_to "Past", classes_teacher_path( :classes=> 3 ) %></li>
              </ul>
            </div>
          </div>
        </div>

        <% @teacher.appointments.each do |a|%>
            <div class="scheduled col-xs-12">
              <div class="col-sm-5 scheduled-image teacher_classes">
                <div class="scheduled-dark"></div>
                <div class="scheduled-white">
                  <%= image_tag("scheduled.png") %>
                </div>
                <div class="scheduled-text">
                  <% if a.end > Time.current.in_time_zone %>
                      <h5>SCHEDULED</h5>
                  <% else %>
                      <h5 class="moneyred">COMPLETED</h5>
                  <% end %>
                  <h1><%= a.start.in_time_zone.strftime('%H:%M %p') %></h1>
                  <p><%= a.start.in_time_zone.strftime('%a %B %d %Y') %> </p>
                </div>
              </div>
              <div class="col-sm-7">
                <div class="col-xs-12">
                  <div class="clearfix flexmodify">
                    <div class="info-mypic col-xs-3 pull-left">
                      <%= user_headimage(a.user) %>
                    </div>
                    <div class="info-eval col-xs-7">
                      <p><%= a.user.first_name %>
                        <%= a.user.last_name %></p>
                      Time Zone: <%= a.user.time_zone %>
                    </div>
                    <div class=" col-xs-2 info-flag">
                    </div>
                  </div>
                  <div class="clearfix ratingnow gotoclass teacherfix">
                    <div class="conatiner-fluid">
                      <% if Time.current.in_time_zone >= a.start.in_time_zone-10.minutes &&
                          Time.current.in_time_zone < a.end.in_time_zone %>
                          <form action="<%= a.appointment_url %>" target="_blank">
                            <button type="submit" name="gotoclass">GO TO CLASS</button>
                          </form>
                      <% elsif Time.current.in_time_zone > a.end.in_time_zone %>
                          <% if a.evaluations.where(evaluatable_type: "Teacher").blank? %>
                              <form action="<%= appointment_path(a.id) %>">
                                <button type="submit" name="rating">Rating Now</button>
                              </form>
                          <% else %>
                              <div class="rated">
                                <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#rating-<%= a.id %>" name="rated">
                                  Rated
                                </button>
                              </div>
                          <% end %>
                      <% elsif Time.current.in_time_zone <= a.start.in_time_zone-10.minutes %>
                          <div class="wait">
                            <button type="submit" name="wait">Coming soon</button>
                          </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="modal fade" id="rating-<%= a.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">

                  <div class="evaluation col-xs-12">
                    <div class="evaluation-button clearfix">
                      <%= link_to "Back" ,classes_teacher_path ,:class=>"pull-left"%>
                      <div class="evaluation-block col-xs-10 col-xs-push-1">
                        <div class="evaluation-me text-center">
                          <%= user_headimage(a.user) %>
                          <h4><%= a.user.first_name %>
                            <%= a.user.last_name %></h4>
                          <p>We hope you had a great lesson! please leave your teacher a review on their profile for other students to see.</p>
                        </div>

                        <div class="evaluation-comment">
                          <h5>Comments</h5>
                          <hr>
                          <div class="user-comment">
                            <%= a.evaluations.where(evaluatable_type: "Teacher").first.try(:comment) %>
                          </div>
                          <textarea id="comment"></textarea>
                          <!-- <textarea class="" placeholder="You can ENTER your comment here!!
                            What did you like about your teacher, and what could your teacher improve?"></textarea> -->
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>