config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/super', as: 'rails_admin'

  def scheme
    if @env['HTTPS'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SSL'] == 'on'
      'https'
    elsif @env['HTTP_X_FORWARDED_SCHEME']
      @env['HTTP_X_FORWARDED_SCHEME']
    elsif @env['HTTP_X_FORWARDED_PROTO']
      @env['HTTP_X_FORWARDED_PROTO'].split(',')[0]
    else
      @env["rack.url_scheme"]
    end
  end

  def ssl?
    scheme == 'https'
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :appointments
  end

  post 'pay2go/return'
  post 'pay2go/notify'

  post "/paypal/webhook" => "paypal#webhook"
  post "/paypal/redirect" => "paypal#redirect" # for paypal return

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations'}
  resources :messages

  resources :users do
    member do
      get :classes
      get :changepassword
      get :remark
      get :editprofile
      get :mytutor
      post :mytutor
    end
    resources :orders do
      member do
        post :checkout_pay2go
        post :checkout_paypal
      end
    end
    resources :available_section, controller: 'user_available_sections'
    member do
      get 'profile'
    end
  end

  resources :teachers do
    member do
      get 'classes' => 'teachers#classes'
      get 'profile' => 'teachers#profile'
      post 'profile' => 'teachers#profile#create'
      get 'calendar' => 'teachers#calendar'
      get 'introduce' => 'teachers#introduce'
      get 'price' => 'teachers#price'
      get 'education' => 'teachers#education'
      get 'youtube' => 'teachers#youtube'
      get 'gathering' => 'teachers#gathering'
    end
    resources :available_section
  end
  get 'apply_teacher_file' => 'teachers#apply_teacher_file'

  resources :appointments do
    resources :evaluations
  end

  resources :student_reservation
  post 'free_trial' =>'student_reservation#free_trial'

  resources :teacher_calendars do
    get 'teacher_available_section' => 'teacher_calendars#teacher_available_section'
    get 'booked_section' => 'teacher_calendars#booked_section'
  end

  get  'scholarship'=> "welcome#scholarship"
  get  'apply_teacher'=> "welcome#apply_teacher"
  get  'teacherwall'=>"welcome#index"
  root 'welcome#mainindex'
  get 'thankyou' => "orders#thankyou"

end

app/views/layouts/_feeback_modal.html.erb
<button type="button" class="message_button" data-toggle="modal" data-target="#message">
    <i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i>
</button>
<div class="modal fade message_modal" id="message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content message_content">

            <div class="modal-header message_header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="message_modal_title" id="myModalLabel">Feedback</h4>
            </div>

              <div class="thankYouFeeback">
                <h3>Thank You!</h3>
                <h4>We will contact you as soon as possible</h4>
                <button type="button" class="finish_button" data-dismiss="modal">完成</button>
              </div>

            <%= form_for Message.new, :html => { :id => 'feebackform' } do |f|  %>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row message_input">
                        <div class="col-xs-3 problem"><%= f.label :problem, "Problem" %></div>
                        <div class="col-xs-9">
                            <%= select(:message,:problem,options_for_select([["BUG", "BUG"],["Suggestion", "Suggestion"], ["Question", "Question"]],"BUG"),{}, {:class=>"selectpicker show-menu-arrow" ,"data-width" =>"100%"} )%></div>
                    </div>
                    <div class="row message_input">
                        <div class="col-xs-3 email"><%= f.label :email, "Email" %></div>
                        <div class="col-xs-9"><%= f.text_field :email, :value => ((current_user.alternate_email.blank? ? current_user.email : current_user.alternate_email) if current_user) ,placeholder:"We will send messages back by this email. ", :class => "form-control" %></div>
                    </div>
                    <div class="row message_input">
                        <div class="col-xs-3 "><%= f.label :message, "Explanation" %></div>
                        <div class="col-xs-9 "><%= f.text_area :message,placeholder:"Message....", :class => "form-control", :id => "message_text", :required =>true %></div>
                    </div>

                </div>
            </div>
            <div class="modal-footer message_footer">
                <button type="button" class="message_cancel" data-dismiss="modal">Close</button>
                <%= f.submit 'SAVE' ,class:"message_save" %>
            </div>

            <% end %>
        </div>

    </div>
</div>



<script>
  $('#feebackform').submit(function() {
    var valuesToSubmit = $(this).serialize();
    $.ajax({
        type: "POST", url: $(this).attr('action'), //sumbits it to the given url of the form
        data: valuesToSubmit,
        dataType: "json", // you want a difference between normal and ajax-calls, and json is standard
        success: function(e){
          console.log(e.message);
          $('.thankYouFeeback').css('display','inline');
          $('.message_footer').css('opacity','0');
          $('.problem').css('opacity','0');
          $('.email').css('opacity','0');
          $('.message_input').css('opacity','0');
          $('#message_text').val('');
          $('#feebackform').css('display','none' );
    }})
    return false; // prevents normal behaviour
  });
</script>

<script>
  $('.message_button').on('click', function(){
    $('.thankYouFeeback').css('display','none');
    $('.problem').css('opacity','1');
    $('.email').css('opacity','1');
    $('.message_input').css('opacity','1');
    $('.message_footer').css('opacity','1');
    $('#feebackform').css('display','block');
  })
</script>

<script>
$("*").each(function (index) {
    var event = $._data(this, "events");
    if (event && "click" in event && event.click.length > 1) {
        console.log("重複 binding 的 tag");
        console.log(this);
    }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazingTutor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'ATlogo.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="msvalidate.01" content="18B9CBF183BEADB8228621693553FD98" />
</head>
<body>
<nav class="navbar navbar-default nav-modify navbar-fixed-top" id="nav">
  <div class="container nav-relative">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header brand-center">
      <% if current_user %>
          <%= link_to teacherwall_path , :class=>"navbar-brand" do%>
              <span class="brand1">Amazing</span><span class="brand2">Tutor</span>
          <% end %>
      <% else %>
          <%= link_to root_path , :class=>"navbar-brand" do%>
              <span class="brand1">Amazing</span><span class="brand2">Tutor</span>
          <% end %>
      <% end %>
    </div>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse clearfix" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
              <%= link_to "Find a tutor",teacherwall_path %>
          <% else %>
              <%= link_to "Find a tutor",new_user_registration_path %>
          <% end %>
        </li>
        <li>
          <%#= link_to("Scholarship", scholarship_path) unless current_user.nil?%>
        </li>
        <li>
          <%= link_to("Apply to Teach", apply_teacher_path)%>
        </li>
        <li>
          <%#= button_tag "Log In", {:class => "loginbutton", :id=>"login" } if !current_user%>
          <%= link_to(t("Log In"), new_session_path(:user))if !current_user%>
        </li>
        <% if current_user %>
            <li class="dropdown">

              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=  user_headimage(current_user) %><%= current_user.display_name %>

                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">

                <li><%= link_to "Dashboard",classes_user_path(current_user) %></li>
                <% if current_user.authority == "teacher" %>
                    <li><%= link_to "教師資訊" ,classes_teacher_path(current_user.get_teacher.id)%></li>
                    <li><%= link_to "授課日曆" ,calendar_teacher_path(current_user.get_teacher.id)%></li>
                <% end %>
                <li>
                  <%= link_to('Log Out', destroy_user_session_path, :method => :delete)%>
                </li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<%= render partial: 'layouts/feeback_modal'  %>

<div class="nav-top"></div>

<%= yield %>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PK4JJZ"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PK4JJZ');</script>
<!-- End Google Tag Manager -->
</body>
</html>

app/views/layouts/ps.html.erb
<script>
  //        var cb = function() {
  //        var l = document.createElement('link'); l.rel = 'stylesheet';
  //        l.href = 'welcome.css';
  //        var h = document.getElementsByTagName('head')[0]; h.parentNode.insertBefore(l, h);
  //        };
  //        var raf = requestAnimationFrame || mozRequestAnimationFrame ||
  //                  webkitRequestAnimationFrame || msRequestAnimationFrame;
  //        if (raf) raf(cb);
  //        else window.addEventListener('load', cb);
</script>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazingTutor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'welcome', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'ATlogo.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="msvalidate.01" content="18B9CBF183BEADB8228621693553FD98" />
</head>
<body>
<nav class="navbar navbar-default nav-modify navbar-fixed-top" id="nav">
  <div class="container nav-relative">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header brand-center">
      <% if current_user %>
          <%= link_to teacherwall_path , :class=>"navbar-brand" do%>
              <span class="brand1">Amazing</span><span class="brand2">Tutor</span>
          <% end %>
      <% else %>
          <%= link_to root_path , :class=>"navbar-brand" do%>
              <span class="brand1">Amazing</span><span class="brand2">Tutor</span>
          <% end %>
      <% end %>
    </div>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse clearfix" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
              <%= link_to "Find a tutor",teacherwall_path %>
          <% else %>
              <%= link_to "Find a tutor",new_user_registration_path %>
          <% end %>
        </li>
        <li>
          <%#= link_to("Scholarship", scholarship_path) unless current_user.nil?%>
        </li>
        <li>
          <%= link_to("Apply to Teach", apply_teacher_path)%>
        </li>
        <li>
          <%#= button_tag "Log In", {:class => "loginbutton", :id=>"login" } if !current_user%>
          <%= link_to(t("Log In"), new_session_path(:user))if !current_user%>
        </li>
        <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user_headimage(current_user) %><%= current_user.display_name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">

                <li><%= link_to "Dashboard",classes_user_path(current_user) %></li>
                <% if current_user.authority == "teacher" %>
                    <li><%= link_to "教師資訊" ,classes_teacher_path(current_user.get_teacher.id)%></li>
                    <li><%= link_to "授課日曆" ,calendar_teacher_path(current_user.get_teacher.id)%></li>
                <% end %>
                <li>
                  <%= link_to('Log Out', destroy_user_session_path, :method => :delete)%>
                </li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="nav-top"></div>

<%= yield %>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PK4JJZ"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PK4JJZ');</script>
<!-- End Google Tag Manager -->
<%#= render :partial=>"welcome/login" %>
<%= render partial: 'layouts/feeback_modal'  %>
</body>
</html>